apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
  namespace: arha-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - name: controller
          image: harbor.pdc.tw/yuchiehpaper/controller:latest
          ports:
            - name: controller
              containerPort: 5000
          volumeMounts:
            - name: information
              mountPath: /app/information
            - name: logs-volume
              mountPath: /app/logdir
          env:
            - name: OPTIMIZER_FUNCTION
              value: "optimize"  # 可改為 optimize 或 uniform 或 most_remaining
        - name: result
          image: harbor.pdc.tw/arha/result:latest
          ports:
            - name: result
              containerPort: 5001
          volumeMounts:
            - name: information
              mountPath: /app/information
        - name: crd-syncer
          image: your-crd-syncer-image:latest
          env:
            - name: FILE_MAP
              value: |
                /data/service.json=services:service-info
                /data/serviceSpec.json=servicespecs:servicespec-info
                /data/subscription.json=subscriptions:subscription-info
                /data/nodestatus.json=nodestatuses:nodestatus-info
            - name: CRD_GROUP
              value: ha.example.com
            - name: CRD_VERSION
              value: v1
            - name: IN_CLUSTER
              value: "true"
          volumeMounts:
            - mountPath: /data
              name: shared-data
      volumes:
        - name: information
          persistentVolumeClaim:
            claimName: arha-system-information
        - name: logs-volume
          persistentVolumeClaim:
            claimName: arha-logs-pvc
        - name: shared-data
          emptyDir: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: arha-node-type
                    operator: In
                    values:
                      - controller-node
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
